### ISSUE TITLE
ImportError: cannot import name 'build_privacy_classifier'

### ISSUE THREAD

**Issue by shravankumar147** [DAVEISHAN/SPAct#1]
Hi,

There is a function missing in the train_ssl_minimax2.py imports. 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3beead59706d> in <module>
     27 
     28 from dl_ft_nov import baseline_dataloader_train_strong, multi_baseline_dataloader_val_strong, collate_fn_train_ucf101, collate_fn_val_ucf101
---> 29 from model import build_r3d_classifier, load_r3d_classifier, ssl_pretrained_load, load_unet, build_privacy_classifier, load_privacy_classifier, ssl_privacy_load
     30 from nt_xent_original import NTXentLoss
     31 from torchvision.utils import save_image

ImportError: cannot import name 'build_privacy_classifier'

**Comment by DAVEISHAN** [comment]
Added [model.py](https://github.com/DAVEISHAN/SPAct/blob/main/anonymization_training/model.py) to resolve the missing imports.
