### ISSUE TITLE
The access to the pretrained privacy attribute detection models

### ISSUE THREAD

**Issue by 5k5000** [DAVEISHAN/SPAct#10]
Hi @DAVEISHAN, thanks for open-sourcing your great work!

Could you provide your pre-trained privacy attribute detection models, which are used for measuring the privacy leakage on the given images?

**Comment by lefteryx** [comment]
did you get the weights or train the model yourself yet by any chance?

**Comment by DAVEISHAN** [comment]
For weights, pl check out our follow-up work: [TeD-SPAD](https://github.com/UCF-CRCV/TeD-SPAD), which improves anonymization for longer videos and performs similarly on UCF101.
