### ISSUE TITLE
ImportError: cannot import name 'ssl_privacy_load'

### ISSUE THREAD

**Issue by shravankumar147** [DAVEISHAN/SPAct#2]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-0d9cef74b936> in <module>
     30 # load_unet, build_privacy_classifier, load_privacy_classifier, ssl_privacy_load
     31 
---> 32 from model import build_r3d_classifier, load_r3d_classifier, ssl_pretrained_load, \
     33 load_unet, ssl_privacy_load
     34 

ImportError: cannot import name 'ssl_privacy_load'

**Comment by DAVEISHAN** [comment]
Added [model.py](https://github.com/DAVEISHAN/SPAct/blob/main/anonymization_training/model.py) to resolve the missing imports.
