### ISSUE TITLE
How to generate ucf101_labeled.txt and ucf101_unlabeled.txt

### ISSUE THREAD

**Issue by shravankumar147** [DAVEISHAN/SPAct#3]
Hi, 

issue in the function => anonymization_training/dl_ft_nov.py -> baseline_dataloader_train_strong       
```
 self.labeled_datapaths = open(os.path.join(cfg.path_folder,'ucf101_labeled.txt'),'r').read().splitlines()
 self.unlabled_datapaths = open(os.path.join(cfg.path_folder,'ucf101_unlabeled.txt'),'r').read().splitlines()
```

Thanks
Shravan

**Comment by DAVEISHAN** [comment]
Modified file to support default UCF annotations: https://github.com/DAVEISHAN/SPAct/blob/main/anonymization_training/dl_ft_nov.py#L30

**Comment by shravankumar147** [comment]
Thanks Ishan
