### ISSUE TITLE
pretrained model weights

### ISSUE THREAD

**Issue by pritamqu** [DAVEISHAN/SPAct#9]
Is it possible to release the pretrained model weights?
Particularly, looking for the `Anonymization` and `Auxiliary Privacy` model weights. 
This would be super helpful. Thanks!

could you please confirm if you're loading actually pretrained weights from the First phase i.e., the Training of the anonymization function in L396 and L398?
https://github.com/DAVEISHAN/SPAct/blob/main/anonymization_training/train_ssl_minimax2.py

```
#L396
ft_model =  load_r3d_classifier(saved_model_file= '/home/c3-0/ishan/privacy_preserving1/ucf101_with_unetrecon/saved_models_and_logs/model_50_bestAcc_0.6262.pth')
#L398
fb_model = ssl_privacy_load(saved_model_file = '/home/c3-0/ishan/privacy_preserving1/vispr_with_unetreocon/saved_models/SSL_unet_recon/model_160.pth')
```

**Comment by lefteryx** [comment]
did you get the weights or train the model yourself yet by any chance?

**Comment by DAVEISHAN** [comment]
Pl find the initializations points and anonymization model from our follow-up work: [TeD-SPAD](https://github.com/UCF-CRCV/TeD-SPAD).
